networks:
    - name: gitea
      subnet: 10.0.0.0/28
    - name: openziti
      subnet: 10.0.1.0/24
    - name: semaphore
      subnet: 10.0.2.0/28
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8rfgalwtjpujyvhweydjh2wnnxyfext87lah4x4mxnyee6ygecsqncvvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL3pxRWlQSGwrNDZPemVv
            R0FjYzhMSzJESUZLN3BtRkRUVHQrekk4TlNJCjY1cENBSFJOeUpqelA1WHZBcjli
            Vzl1WnFneWdnZnpOMXlUV1E5d1ZxRFEKLS0tIDI2cDY3MnlLMzBXRWxpaDlUZzZC
            SGlwMEhZQmMzNFYrcDJJVXFIM05yV2cKqj0HhInwrOnmJ2xkA+Y6QSGbNgbsvZXK
            YwNf/iB8azjZinAxVe72rQzw7oCJXNmQ9PABrW4e8yYSol8g3UFznA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T21:28:40Z"
    mac: ENC[AES256_GCM,data:THAHhkb9ABi+r0nUHnlkndn3kQ7t31nWxHRCzpm1E3trffh4SIfRFQogK//7SrMk/ebgwarJemdd++kEEU7WEukHhBFH4LWmR6eDnGK49soorCieyAy2LcmU2sTmYWDUeKOskYSzOxv2CfaJC5IjRwoItPlKhdICHbMUTm3DMgM=,iv:EMxZ8Wtp7TbXkywhJlAPV+n4T+iVargH2B7fDExJp4Q=,tag:Q+OFhLZnJG5/f3LcVXdjRA==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.9.0
