name: 'Setup Opentofu and Terragrunt'
description: 'Setup Opentofu and Terragrunt'

runs:
  using: 'composite'
  steps:
    - name: Set up Opentofu
      uses: opentofu/setup-opentofu@v1

    - name: Install Terragrunt
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
      shell: bash