---
cloud_provider: oracle_alwaysfree
ingress_rules:
  - protocol: "6"
    source: "0.0.0.0/0"
    min_port: 8086
    max_port: 8086
  - protocol: "6"
    source: "0.0.0.0/0"
    min_port: 1280
    max_port: 1280
  - protocol: "6"
    source: "0.0.0.0/0"
    min_port: 1281
    max_port: 1281
  - protocol: "6"
    source: "0.0.0.0/0"
    min_port: 22
    max_port: 22
